spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  data:
    redis:
      url: redis://default:supersecret@localhost:6379
  mail:
    host: <your-smtp-host>
    port: <your-smtp-port>
    username: <your-smtp-username>
    password: <your-smtp-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

app:
  verification-url: http://localhost:8080/auth/verify
  frontend-base-url: http://localhost:5173
  mail-from: <your-smtp-email>
  jwt-secret: AvengersDoomsdayThreeHundreds2025
  jwt-expiration: 3600