spring:
  datasource:
    url: jdbc:postgresql://backend-auth-postgres:5432/auth
    username: postgres
    password: password

  data:
    redis:
      host: dragonfly
      port: 6379
      password: supersecret

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080